@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

AddressBook *-right-> "1" UniquePersonList

UniquePersonList -right-> Person

Person -up-> "*" Tag

Person *--> Name
Person *--> Email
Person *--> Address
Person *--> "*" LessonSlot
LessonSlot *--> Subject
LessonSlot *--> Day
LessonSlot *--> Time
Person *--> EmergencyContact
Person *--> PaymentStatus
Person *--> Remark
Person --> "attendanceRecords" AttendanceStatus

Class LessonSlot

Class "<<enum>>\nAttendanceStatus" as AttendanceStatus
PaymentStatus -[hidden]right-> Remark
Remark -[hidden]right-> AttendanceStatus
@enduml
