@startuml MarkSequenceDiagram
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":MarkCommandParser" as MarkCommandParser LOGIC_COLOR
participant "m:MarkCommand" as MarkCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "model:Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("mark 1 ps/Paid")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("mark 1 ps/Paid")
activate AddressBookParser

create MarkCommandParser
AddressBookParser -> MarkCommandParser
activate MarkCommandParser

MarkCommandParser --> AddressBookParser
deactivate MarkCommandParser

AddressBookParser -> MarkCommandParser : parse(" 1 ps/Paid")
activate MarkCommandParser

MarkCommandParser -> MarkCommandParser : tokenize args with PREFIX_PAYMENT_STATUS
MarkCommandParser -> MarkCommandParser : parse index from preamble
MarkCommandParser -> MarkCommandParser : parse payment status from ps/

create MarkCommand
MarkCommandParser -> MarkCommand
activate MarkCommand

MarkCommand --> MarkCommandParser
deactivate MarkCommand

MarkCommandParser --> AddressBookParser : m
deactivate MarkCommandParser
MarkCommandParser -[hidden]-> AddressBookParser
destroy MarkCommandParser

AddressBookParser --> LogicManager : m
deactivate AddressBookParser

LogicManager -> MarkCommand : execute(model)
activate MarkCommand

MarkCommand -> Model : getFilteredPersonList()
activate Model
Model --> MarkCommand : lastShownList
deactivate Model

MarkCommand -> MarkCommand : create updated Person
MarkCommand -> Model : setPerson(target, markedPerson)
activate Model
Model --> MarkCommand
deactivate Model

MarkCommand -> Model : updateFilteredPersonList(PREDICATE_SHOW_ALL_PERSONS)
activate Model
Model --> MarkCommand
deactivate Model

create CommandResult
MarkCommand -> CommandResult
activate CommandResult

CommandResult --> MarkCommand
deactivate CommandResult

MarkCommand --> LogicManager : r
deactivate MarkCommand

[<--LogicManager
deactivate LogicManager
@enduml
